### ISSUE TITLE
Datastore?

### ISSUE THREAD

**Issue by Ahmed-90** [AlKass/PiTrol#17]
1. What kind of DB should we use? (should be embedded obviously)
2. What about plugins that need a datastore? or/and custom tables?

**Comment by fadeenk** [comment]
I think for now we should just store data in a file on disk rather than introducing more dependencies and requiring more resources to run the project.

It doesnt make sense to require a complex database server/store to run locally or elsewhere to store some static info that could be easily written to a file.

However, if some plugins must have a datastore I would go with mongoDB since it is more flexible and could be easily used for multiple plugins.

I still think having configs and basic data on disk is better/ more efficient then relying on a datastore.

**Comment by Ahmed-90** [comment]
@fadeenk we have monitoring planned.. you cant write history on a disk its a timebomb 
also mongo needs a server we cant afford that on a Pi so it should be embedded

i will create a poll on FB with some base requirements

**Comment by AlKass** [comment]
I'd suggest that monitoring data is to be held in the browser instead. We could look into some offline-first database options

**Comment by Ahmed-90** [comment]
browser? offline first ? noooooo.. what if the user logged in from different machine? lost browser? didn't login for ages? browser storage limits? 

this is very unreliable for such project keep it simple with a nice

**Comment by AlKass** [comment]
There are get-arounds to the possible leaks you pointed out but i'd say let's consider something as lightweight as rethinkdb or redis, or we could leave it completely up to the user to decide how he or she wants to store data

**Comment by fadeenk** [comment]
We could go the adapters apporach. Build an adapter that is in memory store (just a giant object for simple plugins). And it can be replaced by custom adapter that add support for other sotres/dbs like redis, mongo whichever db supports most of the adapters
